export const PRODUCT_OPTIONS = {
  FORMS_EN: [
    'Crushed', 'Cushed', 'Cut', 'Flowers', 'Leaves', 'Petal', 'Petals', 'Powder', 'Seeds', 'Sifting', 'T.B.C'
  ],
  FORMS_AR: [
    'أكياس شاي', 'أوراق', 'بتلات', 'بذور', 'حبوب', 'زهور', 'مجروش', 'مطحون', 'قطع'
  ],
  ACTIVE_INGREDIENTS_EN: [
    'Anethole', 'Anthocyanins', 'Antioxidant and natural diuretic', 'Antioxidants', 'Apiol', 'Apigenin', 'Azulene',
    'Camphor', 'Carotenoids', 'Carvacrol', 'Carvone', 'Chlorogenic Acid', 'Citral', 'Coriandrol', 'Dietary Fiber',
    'Eugenol', 'Fenchone', 'Flavonoids', 'Limonene', 'Linalool', 'Menthol', 'Menthone', 'Myristicin', 'Quercetin',
    'Rosmarinic Acid', 'Sesamol', 'Sesamin', 'Steviol Glycosides', 'Thymol', 'Thymoquinone', 'Triterpenoids'
  ],
  ACTIVE_INGREDIENTS_AR: [
    'أبيجينين', 'أبيول', 'أزولين', 'ألياف غذائية', 'أنيثول', 'أنثوسيانينات', 'أوجينول', 'ترايتيربينويدات',
    'ثيمول', 'ثيموكينون', 'جليكوسيدات ستيفيول', 'حمض الرزمارينيك', 'حمض الكلوروجينيك', 'سيسامول', 'سيسامين',
    'سيترال', 'فينشون', 'فلافونيدات', 'كافور', 'كارفاكرول', 'كارافون', 'كاروتينويدات', 'كيرسيتين', 'كورياندرول',
    'ليمونين', 'لينالول', 'مضادات الأكسدة', 'منتول', 'منتون', 'ميريستيسين'
  ],
  HARVEST_SEASON_EN: [
    'April', 'April to June', 'April to July', 'April to November', 'April to October', 'August',
    'December to March', 'February to March', 'Januarly to April', 'July', 'July to October', 'June',
    'June to August', 'June to october', 'May', 'May to October', 'May to September', 'November to April',
    'November to January', 'November to July'
  ],
  HARVEST_SEASON_AR: [
    'أبريل', 'أبريل إلى أكتوبر', 'أبريل إلى يونيو', 'أبريل إلى يوليو', 'أبريل إلى نوفمبر', 'أغسطس',
    'ديسمبر إلى مارس', 'فبراير إلى مارس', 'مايو', 'مايو إلى سبتمبر', 'مايو إلى أكتوبر',
    'محصول صيفي يونيو إلى نوفمبر، محصول شتوي ديسمبر إلى مارس', 'نوفمبر إلى أبريل', 'نوفمبر إلى يناير',
    'نوفمبر إلى يوليو', 'يناير إلى أبريل', 'يونيو', 'يونيو إلى أغسطس', 'يونيو إلى أكتوبر', 'يوليو', 'يوليو إلى أكتوبر'
  ],
  AVAILABILITY_EN: [
    'April to June', 'April to September', 'Available all year long', 'Available all year round',
    'December to July', 'July to October', 'March to August', 'March to June', 'November to July',
    'summer crop June to November, Winter crop December to march'
  ],
  AVAILABILITY_AR: [
    'أبريل إلى سبتمبر', 'أبريل إلى يونيو', 'ديسمبر إلى يوليو', 'مارس إلى أغسطس', 'مارس إلى يونيو',
    'متوفر على مدار السنة', 'متاح طوال العام', 'محصول صيفي يونيو إلى نوفمبر، محصول شتوي ديسمبر إلى مارس',
    'نوفمبر إلى يوليو', 'يوليو إلى أكتوبر'
  ],
  CONTAINER_CAPACITY_EN: [
    'Anise seeds: 960 bags, each containing 25 kilograms net.',
    'Basil leaves: 650 cartons, each containing 10 kilograms net.',
    'Basil TBC: 560 bags, each containing 25 kilograms net.',
    'Broad Beans: about 480 pepper bags x 25 kg net.',
    'Calendula flowers: 650 bags, each containing 12.5 kilograms net.',
    'Calendula Petals: 700 bags, each containing 10 kilograms net.',
    'Caraway seeds: 960 bags, each containing 25 kilograms net.',
    'Celery seeds: about 960 pepper bags x 25 kg net.',
    'Chamomile flowers: 650 cartons, each containing 12.5 kilograms net.',
    'Chamomile Powder: 450 bags, each containing 20 kilograms net.',
    'Coriander seeds: 560 bags, each containing 25 kilograms net.',
    'Cumin seeds: about 960 pepper bags x 25 kg net.',
    'Cut Hibiscus: 440 bags, each containing 20 kilograms net.',
    'Cut Lemon Grass 1-2 cm: 667 bags, each containing 15 kilograms net.',
    'Dill leaves: 480 bags, each containing 25 kilograms net.',
    'Fennel seeds: 960 bags, each containing 25 kilograms net.',
    'Fenugreek seeds: about 960 pepper bags x 25 kg net.',
    'Freekha seeds: about 880 bags x 25 kg net.',
    'Garlic seeds: about 400 mesh bags x 5 kg net.',
    'Ground Basil: 600 bags, each containing 20 kilograms net.',
    'Ground Chamomile: 560 bags, each containing 25 kilograms net.',
    'Ground Moringa: 480 bags, each containing 25 kilograms net.',
    'Ground Stevia: 480 bags, each containing 25 kilograms net.',
    'Guava leave: 650 carton box X 10 kg net; Mesh bags: 600 bags x 20 kg net.',
    'Henna crushed: about 280 bags x 25kg net.',
    'Hibiscus leaves: 650 cartons, each containing 13 kilograms net.',
    'Hibiscus TBC: 1000 bags, each containing 25 kilograms net.',
    'Jew’s Mallow leaves: 700 cartons, each containing 5 kilograms net.',
    'Lemon verbena crushed: about 480 pepper bags x 25kg net.',
    'Marjoram: 550 bags, each containing 20 kilograms net.',
    'Moringa leaves: 650 cartons, each containing 10 kilograms net.',
    'Moringa TBC: 560 bags, each containing 25 kilograms net.',
    'Nettle crushed: about 480 pepper bags x 25kg net.',
    'Nigella Sativa seeds: 960 bags, each containing 25 kilograms net.',
    'Onion: about 960 bags x 15 kg net.',
    'Parsley Leaves: 450 bags, each containing 20 kilograms net.',
    'Peppermint leaves: 650 cartons, each containing 10 kilograms net.',
    'Peppermint Powder: 480 bags, each containing 25 kilograms net.',
    'Peppermint TBC: 560 bags, each containing 25 kilograms net.',
    'Red rose flower: about 650 carton box x 10 kg net.',
    'Rosemary: 450 bags, each containing 20 kilograms net.',
    'Sage leave: about 800 pepper bags x 12.5 kg net.',
    'Senna leave: about 550 pepper bags x 20 kg net.',
    'Sesame seeds: 720 bags, each containing 25 kilograms net.',
    'Spearmint leaves: 650 cartons, each containing 10 kilograms net.',
    'Spearmint Powder: 480 bags, each containing 25 kilograms net.',
    'Spearmint TBC: 560 bags, each containing 25 kilograms net.',
    'Stevia leaves: 650 cartons, each containing 15 kilograms net.',
    'Stevia TBC: 560 bags, each containing 25 kilograms net.',
    'Sunflower seeds: about 960 pepper bags x 25 kg net.',
    'Thyme: 450 bags, each containing 20 kilograms net.',
    'verbasci about: 650 carton box X 7 kg net.',
    'Wight Beans: about 480 pepper bags x 25 kg net.',
    'summer whole year, winter march to may'
  ],
  CONTAINER_CAPACITY_AR: [
    'أوراق الاستيفيا: 650 كرتونة، تحتوي كل واحدة على 15 كجم صافي. استيفيا مطحونة: 480 كيس، كل كيس يحتوي على 25 كجم صافي. استيفيا (TBC): 560 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'أوراق الجوافة: 650 صندوق كرتون × 10 كجم صافي. أكياس شبكية: 600 كيس × 20 كجم صافي.',
    'أوراق الريحان: 650 كرتونة، تحتوي كل واحدة على 10 كجم صافي. ريحان مطحون: 600 كيس، كل كيس يحتوي على 20 كجم صافي. ريحان (TBC): 560 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'أوراق الشبت: 480 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'أوراق الملوخية: 700 كرتونة، تحتوي كل واحدة على 5 كجم صافي.',
    'أوراق المورينجا: 650 كرتونة، تحتوي كل واحدة على 10 كجم صافي. مورينجا مطحونة: 480 كيس، كل كيس يحتوي على 25 كجم صافي. مورينجا (TBC): 560 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'أوراق المريمية: 800 كيس ورقي × 12.5 كجم صافي.',
    'أوراق النعناع: 650 كرتونة، تحتوي كل واحدة على 10 كجم صافي. نعناع (TBC): 560 كيس، كل كيس يحتوي على 25 كجم صافي. بودرة النعناع: 480 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'أوراق النعناع الأخضر: 650 كرتونة، تحتوي كل واحدة على 10 كجم صافي. نعناع أخضر (TBC): 560 كيس، كل كيس يحتوي على 25 كجم صافي. بودرة النعناع الأخضر: 480 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'أوراق البقدونس: 450 كيس، كل كيس يحتوي على 20 كجم صافي.',
    'أوراق السنامكي: 550 كيس ورقي × 20 كجم صافي.',
    'أوراق الكركديه: 650 كرتونة، تحتوي كل واحدة على 13 كجم صافي. كركديه مقطع: 440 كيس، كل كيس يحتوي على 20 كجم صافي. كركديه (TBC): 1000 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'إكليل الجبل: 450 كيس، كل كيس يحتوي على 20 كجم صافي.',
    'بذور الكراوية: 960 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'بذور الكزبرة: 560 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'بذور الكرفس: 960 كيس ورقي × 25 كجم صافي.',
    'بذور الشمر: 960 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'بذور الكمون: 960 كيس ورقي × 25 كجم صافي.',
    'بذور الحلبة: 960 كيس ورقي × 25 كجم صافي.',
    'بذور السمسم: 720 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'بذور عباد الشمس: 960 كيس ورقي × 25 كجم صافي.',
    'بذور الينسون: 960 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'بذور حبة البركة: 960 كيس، كل كيس يحتوي على 25 كجم صافي.',
    'بذور الثوم: 400 كيس شبكي × 5 كجم صافي.',
    'بردقوش: 550 كيس، كل كيس يحتوي على 20 كجم صافي.',
    'بصل: 960 كيس × 15 كجم صافي.',
    'بتلات الكاليندولا: 700 كيس، كل كيس يحتوي على 10 كجم صافي.',
    'حناء مجروشة: 280 كيس × 25 كجم صافي.',
    'حبوب الفريكة: 880 كيس × 25 كجم صافي.',
    'زعتر: 450 كيس، كل كيس يحتوي على 20 كجم صافي.',
    'زهور البابونج: 650 كرتونة، تحتوي كل واحدة على 12.5 كجم صافي. بابونج مطحون: 560 كيس، كل كيس يحتوي على 25 كجم صافي. بودرة البابونج: 450 كيس، كل كيس يحتوي على 20 كجم صافي.',
    'زهور الكاليندولا: 650 كيس، كل كيس يحتوي على 12.5 كجم صافي.',
    'زهرة الورد الأحمر: 650 صندوق كرتون × 10 كجم صافي.',
    'عشب الليمون المقطع (1-2 سم): 667 كيس، كل كيس يحتوي على 15 كجم صافي.',
    'فاصولياء بيضاء: 480 كيس ورقي × 25 كجم صافي.',
    'فول: 480 كيس ورقي × 25 كجم صافي.',
    'فيرباسكي: 650 صندوق كرتون × 7 كجم صافي.',
    'قراص مجروش: 480 كيس ورقي × 25 كجم صافي.',
    'لويزة الليمون المجروشة: 480 كيس ورقي × 25 كجم صافي.',
    'المواسم: الصيف طوال العام، الشتاء مارس إلى مايو.'
  ],
  NATURAL_WONDERS_EN: [
    'A healthy alternative to sugar', 'Aids in digestion and suppresses appetite',
    'A natural remedy to calm coughs and reduce respiratory inflammation',
    'A natural stomach soother, helping to calm and soothe the digestive system',
    'Alleviates skin inflammation and irritation', 'Antioxidants', 'Boosts concentration and alleviates muscle aches',
    'Boosts hair and skin health and improves respiratory function', 'Dental health',
    'Enhances cardiac and digestive health, and fortifies the immune system',
    'Enhances digestion and alleviates bowel spasms', 'Enhances digestion and helps manage menopausal discomforts',
    'Enhances digestion and promotes blood cell production', 'Enhances digestion and promotes healthy skin',
    'Enhances digestion and relieves bloating', 'Helps fight depression and regulate blood sugar levels',
    'Helps maintain a healthy heart and reduces the severity of menstrual cramps',
    'Improves digestion and boosts brain health', 'Improves digestion and promotes healthy skin',
    'Improves digestion and reduces muscular tension', 'Improves digestion and relieves irritable bowel syndrome',
    'Improves respiratory health and reduces congestion', 'Possesses anti-cancer effects, particularly for breast cancer',
    'Promotes a healthy digestive system and supports overall well-being', 'Promotes bone health and reduces cholesterol',
    'Promotes faster wound healing and restores skin\'s natural moisture',
    'Promotes healthy breathing and reduces stress and tension', 'Promotes immunity and alleviates cough',
    'Promotes the Nervous System health and reduces inflammations',
    'Reduces blood-sugar levels and promotes healthy heart', 'Reduces blood-sugar levels and reduces inflammations',
    'Reduces stress and improves digestion', 'Reduces stress and treats headaches',
    'Relieves menstrual cramps and promotes wound healing',
    'Revitalizes skin and hair, and boosts liver and brain health. Aids in regulating blood sugar and decreasing inflammation',
    'Rich in antioxidants that help prevent diseases', 'Rich in minerals',
    'Rich in nutrients and has anti-inflammatory properties', 'Rich in Vitamin K, which enhances bone health',
    'Significantly lowers blood pressure and enhances liver health. Boosts your weight loss and lowers your cholesterol naturally',
    'Soothes stress, insomnia, and promotes relaxation', 'Stimulates hair growth and improves nervous system health',
    'Supports cardiovascular health and decreases inflammation', 'Supports heart health and lowers blood pressure'
  ],
  NATURAL_WONDERS_AR: [
    'بديل صحي للسكر', 'ثري بالمعادن', 'غني بفيتامين K الذي يعزز صحة العظام',
    'غني بالعناصر الغذائية ويمتلك خصائص مضادة للالتهابات', 'غني بمضادات الأكسدة التي تساعد في الوقاية من الأمراض',
    'علاج طبيعي لتهدئة السعال وتقليل التهاب الجهاز التنفسي', 'مضادات الأكسدة', 'مضاد للأكسدة ومدر طبيعي للبول',
    'مهدئ طبيعي للمعدة ويساعد على تحسين الهضم', 'يحسن الهضم ويعزز صحة البشرة', 'يحسن الهضم ويخفف تقلصات الأمعاء',
    'يحسن الهضم ويخفف متلازمة القولون العصبي', 'يحسن الهضم ويقلل من التوتر العضلي',
    'يحسن الهضم ويساعد في إدارة متاعب انقطاع الطمث', 'يحسن الهضم ويعزز إنتاج خلايا الدم', 'يحسن الهضم ويخفف الانتفاخ',
    'يحسن صحة الجهاز التنفسي ويقلل الاحتقان', 'يخفف التوتر والأرق ويساعد على الاسترخاء',
    'يخفف من آلام الدورة الشهرية ويساعد على التئام الجروح', 'يخفف التهاب الجلد وتهيجه',
    'يخفض ضغط الدم بشكل كبير ويعزز صحة الكبد', 'يقلل التوتر ويحسن الهضم', 'يقلل التوتر ويعالج الصداع',
    'يقلل مستويات السكر في الدم ويعزز صحة القلب', 'يقلل مستويات السكر في الدم ويعزز صحة الدماغ',
    'يقلل مستويات السكر في الدم ويقلل الالتهابات', 'يمتلك تأثيرات مضادة للسرطان، خاصة لسرطان الثدي',
    'ينشط البشرة والشعر، ويعزز صحة الكبد والدماغ. يساعد في تنظيم سكر الدم وتقليل الالتهابات',
    'يساعد في الحفاظ على صحة القلب ويقلل من شدة تقلصات الدورة الشهرية',
    'يساعد في مكافحة الاكتئاب وتنظيم مستويات السكر في الدم', 'يساعد في الهضم ويقلل الشهية',
    'يوفر الراحة لأعراض الجهاز التنفسي وآلام الدورة الشهرية',
    'يعزز التئام الجروح بشكل أسرع ويعيد الرطوبة الطبيعية للبشرة', 'يعزز الصحة العامة للجهاز الهضمي',
    'يعزز التنفس الصحي ويقلل التوتر والضغط العصبي', 'يعزز التركيز ويخفف آلام العضلات',
    'يعزز صحة الشعر والبشرة ويحسن وظيفة الجهاز التنفسي', 'يعزز صحة العظام ويقلل الكوليسترول',
    'يعزز صحة القلب والجهاز الهضمي، ويقوي جهاز المناعة', 'يعزز صحة القلب ويخفض ضغط الدم',
    'يعزز فقدان الوزن ويخفض الكوليسترول بشكل طبيعي', 'يعزز المناعة ويخفف السعال',
    'يدعم صحة القلب والأوعية الدموية ويقلل الالتهابات', 'يحفز نمو الشعر ويحسن صحة الجهاز العصبي',
    'يعزز صحة الجهاز العصبي ويقلل الالتهابات', 'صحة الأسنان'
  ]
};
